### ISSUE TITLE
Need a way to resize height (and width?) of editor on the fly

### ISSUE THREAD

**Issue by sebnitu** [OscarGodson/EpicEditor#160]
Here's how I'm currently doing this:

``` js
eEditor.on('load', function () {
    editor_markdown.resizable();
});

editor_markdown.bind( "resize", function(event, ui) {
    eEditor.load();
});
```

`editor_markdown` is the editors container.

I have to call jQuery UI's resizable method on the wrapper after it's been loaded or else it will override the HTML it puts in it with the iframe. I then have to bind the resize trigger so I can load EpicEditor again so it resizes itself to fit in the newly resized container. But after that it overrides the resizable HTML elements so I can't resize it further.

It would be nice if I had a `eEditor.resetHeight()` to use, then I could just use it as a callback on resizable resize event.

The only other workaround I can think of is injecting a second element along side the editors container and layer them with equal heights. Then I can use `alsoResize` them together so when I resize the second element, the editors container also adjusts and then I'd reload the editor like I do above.

Thoughts? Am I coming at this the wrong way?

**Comment by OscarGodson** [comment]
When I added the `resetWidth` function awhile ago I originally tried to do it as `resetDimensions` or something. However, I was having an issue where when you resized the width the height would grow no matter what by a certain amount of pixels. I couldn't figure it out for the life of me so I gave up and ended up just doing `resetWidth`. 

So, this _should_ be easy, but I couldn't figure it out last time. I do it on the initial load with `setupIframeStyles` but running that same call again increases the height even when the height doesn't change. GRRR. I'll look into it more tho.

I've added it to the 0.1.2 release and see if I can get it in.

**Comment by sebnitu** [comment]
Sweet, thanks man! 

In the mean time, I've got a working solution. Incase anyone else wants to do something similar, what I did is this:

**Markup**

``` html
<div id="epiceditor_wrap">
    <div id="epiceditor_box"> ... EpicEditors Container... </div>
    <div id="epiceditor_resizable"></div>
    <div id="epiceditor_resizable_mask"></div>
</div>
```

**JavaScript**

``` javascript
$('#epiceditor_resizable').resizable({
    alsoResize : '#epiceditor_wrap, #epiceditor_box',
    handles : 's'
})

// If we have a previously saved height
if ( '' != ee_height ) {
    ee_box.height( ee_height + 'px' );
    ee_wrap.height( ee_height + 'px' );
}

ee_resize.bind( "resizestart", function(event, ui) {
    ee_box.css({ 'opacity' : '0.5' });
    ee_resize_mask.show().height( ee_box.height() );
});

ee_resize.bind( "resizestop", function(event, ui) {
    // Reload EE so it fits it's container again
    eEditor.load();

    ee_box.css({ 'opacity' : '1' });
    ee_resize_mask.hide().height( '100%' );

    // Save editors height
    setUserSetting('ee_height', ee_wrap.height() );
});

```

**CSS**

``` css
#epiceditor_wrap {
    position: relative;
    height: 380px;
}
#epiceditor_box {
    position: relative;
    z-index: 2;
    height: 380px;
}
#epiceditor_resizable {
    position: absolute;
    z-index: 1;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    padding-bottom: 20px;
}
#epiceditor_resizable_mask {
    position: absolute;
    z-index: 3;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: none;
}
```

The reason I have that resize mask div is to cover up EpicEditor while the height is being adjusted. The problem was that if I moused over it while resizing, it would lose focus on the handle.

Video demo: http://cl.ly/IEJZ
