### ISSUE TITLE
Make CSS csslint compliant

### ISSUE THREAD

**Issue by v1p** [OscarGodson/EpicEditor#398]
I love the EpicEditor, but the provided css i not usable as my project have strict csslint in works. It'll be great to make the css more compliant to available linters, so as there's less friction in using it.

Thanks!

**Comment by OscarGodson** [comment]
Might be hard. Everyone has different rules for their CSS.

Just one example, the following CSS I've seen written in these forms in different projects:

``` css
.this { color: #000; }
.this2 { color: #f00; }
```

``` css
.this { 
  color: #000; }
.this2 {
  color: #f00; }
```

``` css
.this { 
  color: #000;
}
.this2 {
  color: #f00;
}
```

Would all of those be compliant with csslint?
