### ISSUE TITLE
Revamp of theming

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#48]
Putting a stub here because i don't really like the current theming style, but im also not entirely sure how to make it better.

**Comment by OscarGodson** [comment]
After fixing #59 we can get rid of the prepending of the namespace and state (edit or preview) in our styles so we don't have to worry about styles conflicting. We could have this structure:

``` text
-- css/
---- preview/
------ github.css
------ epic-preview-dark.css
---- editor/
------ epic-dark.css
------ epic-light.css
---- base/
------ epiceditor.css
```

Then the CSS could be swapped out from like:

``` css
.epiceditor-preview h1{
  font-size:28px;
  color:#000;
}
```

to simply:

``` css
h1{
  font-size:28px;
  color:#000;
}
```

This would make it easier for everyone.
