### ISSUE TITLE
Need to override container margins in faux fullscreen

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#98]
I noticed with our styles for `#example-1` we have a `20px` margin:

``` css
#example-1 {
    border: 1px solid #000000;
    border-radius: 3px 3px 3px 3px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.75);
    height: 349px;
    margin-top: 20px; /* HERE */
}
```

This causes this: 

![screenshot](https://img.skitch.com/20120510-bwcctrjtgaj9kpdushq82wkm3b.png)

Pretty important...
